theme = "catppuccin_macchiato"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.auto-save.after-delay]
enable = true
timeout = 3000

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type", "version-control"]

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
